### ISSUE TITLE
comoNetInflow_1996_2008.txt not in the Data folder

### ISSUE THREAD

**Issue by samarthsing** [mxgiuliani00/LakeComo#1]
line 16 of the test/settings_lakeComo_CSPA.txt mentions the requirement of comoNetInflow_1996_2008.txt in the data folder, which is missing.

**Comment by mxgiuliani00** [comment]
Thank you for the remark. We removed that file as it was proprietary of Consorzio dell’Adda; we have now updated the full repository to work with simulated inflow data (and corresponding perfect forecasts)
